development:
  adapter: postgresql
  encoding: utf8
  database: project_c18_shortener_url_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_c18_shortener_url_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_c18_shortener_url_development
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
