# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4b3040ad61de18b515995e4b9223023b61b0d364f1a7ea18a0373ddce7f541db55af9b5330fec935e33d84761405122bf087e4d1f1877f380d8e4b154862667

test:
  secret_key_base: 122e6a330c78169ba0e6531d66015434663ebca3a78e3b003c647f3bbe895acd0514cbe84cd3500f17ee9e21bb748867e603f6a408138c6910e0da0cb4d63a83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
